#         Copyright Leonardo Banderali 2017 - 2017.
# Distributed under the Boost Software License, Version 1.0.
#    (See accompanying file LICENSE_1_0.txt or copy at
#          http://www.boost.org/LICENSE_1_0.txt)

CXX?=g++

simple_test: simple_test.cpp
	$(CXX) -std=c++14 -I../include simple_test.cpp -o $@
